version: '3'
services:
  mysql:
    image: 'mysql:8.0.35'
    container_name: review-blog
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=blog
      - MYSQL_PASSWORD=1234
    volumes:
      - ./.data/mysql:/var/lib/mysql
